/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.example.Gestionale;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nano_machine
 */
public class AggiungiAlMenuDialog extends javax.swing.JDialog {
    
    public static final int CONFERMA = 0;
    public static final int ANNULLA = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiAlMenuDialog.class.getName());
    
    private Pietanza pietanza;
    private String pathImmagine; 
    private BufferedImage bufferedImage;
    private int returnValue = ANNULLA;
    private boolean immagineCambiata = false;
    
    /**
     * Creates new form EditMenuDialog
     */
    public AggiungiAlMenuDialog(java.awt.Frame parent, Pietanza pietanza) {
        super(parent, true);
        initComponents();
        
        //riempe tutti i campi in base all'oggetto passato
        if (pietanza.getPathImmagine() != null) {
            File f = new File(pietanza.getPathImmagine());
            try {
                bImmagine.setIcon(new ImageIcon(ImageIO.read(f)));//converte il file in icona is scala
                bImmagine.setText(null);
            } catch (IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Si è verificato un problema aprendo il file immagine.", "ERRORE", JOptionPane.WARNING_MESSAGE);
            }             
        }
        
        tfNomePietanza.setText(pietanza.getNomePietanza());
        cbPortata.setSelectedItem(pietanza.getPortata());
        taIngredienti.setText(pietanza.getIngredienti());
        taAllergeni.setText(pietanza.getAllergeni());
        taAltreNote.setText(pietanza.getNote());
        cbSenzaGlutine.setSelected(pietanza.isSenzaGlutine());        
        cbSenzaLattosio.setSelected(pietanza.isSenzaLattosio());       
        cbVegetariano.setSelected(pietanza.isVegetariano());       
        cbVegano.setSelected(pietanza.isVegano());
        tfPrezzo.setText(Float.toString(pietanza.getPrezzo()));
        
        this.pietanza = new Pietanza();
        this.pietanza.setPathImmagine(pietanza.getPathImmagine());
    }
    
    public AggiungiAlMenuDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        pietanza = new Pietanza();
    }
    
    public int showDialog() {
        this.setLocationRelativeTo(SwingUtilities.getWindowAncestor(this));
        this.setVisible(true);        
        return returnValue;
    }

    public Pietanza getPietanza() {
        return pietanza;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        erroreMenu = new javax.swing.JOptionPane();
        lAltreNote = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAltreNote = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAllergeni = new javax.swing.JTextArea();
        lAllergeni = new javax.swing.JLabel();
        cbSenzaLattosio = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        cbVegano = new javax.swing.JCheckBox();
        cbVegetariano = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        cbPortata = new javax.swing.JComboBox(Portata.values());
        bImmagine = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taIngredienti = new javax.swing.JTextArea();
        lIngredienti = new javax.swing.JLabel();
        lPortata = new javax.swing.JLabel();
        cbSenzaGlutine = new javax.swing.JCheckBox();
        tfNomePietanza = new javax.swing.JTextField();
        lNomePietanza = new javax.swing.JLabel();
        bAnnulla = new javax.swing.JButton();
        bConferma = new javax.swing.JButton();
        tfPrezzo = new javax.swing.JTextField();
        lPrezzo = new javax.swing.JLabel();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setDialogTitle("Scegli l'immagime del piatto");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Immagini", "png", "jpg"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lAltreNote.setText("Altre note");

        taAltreNote.setColumns(20);
        taAltreNote.setRows(5);
        jScrollPane3.setViewportView(taAltreNote);

        taAllergeni.setColumns(20);
        taAllergeni.setRows(5);
        jScrollPane1.setViewportView(taAllergeni);

        lAllergeni.setText("Allergeni");

        cbSenzaLattosio.setText("Senza lattosio");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbVegano.setText("Vegano");

        cbVegetariano.setText("Vegetariano");

        bImmagine.setText("Immagine");
        bImmagine.setIconTextGap(0);
        bImmagine.addActionListener(this::bImmagineActionPerformed);

        taIngredienti.setColumns(20);
        taIngredienti.setRows(5);
        jScrollPane2.setViewportView(taIngredienti);

        lIngredienti.setText("Ingredienti");

        lPortata.setText("Portata");

        cbSenzaGlutine.setText("Opzione senza glutine");

        tfNomePietanza.setToolTipText("Nome Piatto");

        lNomePietanza.setText("Nome pietanza");

        bAnnulla.setText("Annulla");
        bAnnulla.addActionListener(this::bAnnullaActionPerformed);

        bConferma.setText("Conferma");
        bConferma.addActionListener(this::bConfermaActionPerformed);

        lPrezzo.setText("Prezzo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVegetariano)
                            .addComponent(cbSenzaGlutine)
                            .addComponent(cbSenzaLattosio)
                            .addComponent(cbVegano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lAllergeni)
                            .addComponent(lAltreNote)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))
                        .addGap(18, 70, Short.MAX_VALUE)
                        .addComponent(bAnnulla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bConferma))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomePietanza, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNomePietanza)
                            .addComponent(cbPortata, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPortata))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lIngredienti))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPrezzo)
                            .addComponent(tfPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lIngredienti)
                            .addComponent(lNomePietanza)
                            .addComponent(lPrezzo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNomePietanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lPortata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPortata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAnnulla)
                            .addComponent(bConferma))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbSenzaGlutine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVegetariano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVegano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSenzaLattosio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lAllergeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lAltreNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bImmagineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImmagineActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { //Se viene scelto un file
            File immagineIntera = jFileChooser1.getSelectedFile();
            Image tempImg = null;
            
            try {
                //ridimensionamento immagine
                tempImg = ImageIO.read(immagineIntera).getScaledInstance(120, 120, Image.SCALE_SMOOTH);   //Riduce (o aumenta) la dimensione dell'immagine in modo che entri nel JButton            
                bufferedImage = new BufferedImage(120, 120, BufferedImage.TYPE_INT_ARGB);    //https://www.baeldung.com/java-image-bufferedimage-conversion
                bufferedImage.getGraphics().drawImage(tempImg, 0, 0, null);
                immagineCambiata = true;
            } catch (IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Si è verificato un problema aprendo il file.", "ERRORE", JOptionPane.WARNING_MESSAGE);
            }
            
            bImmagine.setIcon(new ImageIcon(tempImg));
            bImmagine.setText(null);
        } else {
            System.out.println("Selezione icona: operazione annullata dall'utente");
        }
    }//GEN-LAST:event_bImmagineActionPerformed

    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
        returnValue = ANNULLA;
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

    private void bConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfermaActionPerformed
        pietanza.setAllergeni(taAllergeni.getText());
        pietanza.setIngredienti(taIngredienti.getText());
        pietanza.setNomePietanza(tfNomePietanza.getText());
        pietanza.setNote(taAltreNote.getText());
        pietanza.setSenzaGlutine(cbSenzaGlutine.isSelected());
        pietanza.setSenzaLattosio(cbSenzaLattosio.isSelected());
        pietanza.setVegetariano(cbVegetariano.isSelected());
        pietanza.setVegano(cbVegano.isSelected());
        pietanza.setPortata((Portata) cbPortata.getSelectedItem());
        try {
            pietanza.setPrezzo(Float.parseFloat(tfPrezzo.getText()));
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Inserire un prezzo valido. Assicurati di usare il punto al posto della virgola.", "Errore prezzo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (immagineCambiata) {
            try {
                File file = new File(String.format("./src/main/resources/ImmaginiPietanze/immagine_scalata_%s_%s-%s.png", pietanza.getNomePietanza(), LocalDate.now(), LocalTime.now()));
                ImageIO.write(bufferedImage, "PNG", file);
                pietanza.setPathImmagine(file.getAbsolutePath());
            } catch(IOException ex) {
                JOptionPane.showMessageDialog(this, "L'immagine non è stata scelta o qualcosa è andato storto nel salvataggio dell'immagine su disco", "Errore IO", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        
        returnValue = CONFERMA;
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bConfermaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AggiungiAlMenuDialog dialog = new AggiungiAlMenuDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bConferma;
    private javax.swing.JButton bImmagine;
    private javax.swing.JComboBox<String> cbPortata;
    private javax.swing.JCheckBox cbSenzaGlutine;
    private javax.swing.JCheckBox cbSenzaLattosio;
    private javax.swing.JCheckBox cbVegano;
    private javax.swing.JCheckBox cbVegetariano;
    private javax.swing.JOptionPane erroreMenu;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lAllergeni;
    private javax.swing.JLabel lAltreNote;
    private javax.swing.JLabel lIngredienti;
    private javax.swing.JLabel lNomePietanza;
    private javax.swing.JLabel lPortata;
    private javax.swing.JLabel lPrezzo;
    private javax.swing.JTextArea taAllergeni;
    private javax.swing.JTextArea taAltreNote;
    private javax.swing.JTextArea taIngredienti;
    private javax.swing.JTextField tfNomePietanza;
    private javax.swing.JTextField tfPrezzo;
    // End of variables declaration//GEN-END:variables
}
