/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Gestionale;

import com.fasterxml.jackson.core.type.TypeReference;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 *
 * @author nano_machine
 */
public class App extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());
    private ArrayList<Pietanza> menu;
    private ArrayList<Tavolo> sala;
    private ObjectMapper objectMapper;

    /**
     * Creates new form Main
     */
    public App() {
        initComponents();
        
        objectMapper = new ObjectMapper();
        
        try {
        sala = objectMapper.readValue(new File("sala.json"), new TypeReference<ArrayList<Tavolo>>() {});
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Il programma ha riscontrato un problema nel caricamento dei dati di sala", "ERRORE", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
            sala = new ArrayList<Tavolo>();
        }
        try {
        menu = objectMapper.readValue(new File("menu.json"), new TypeReference<ArrayList<Pietanza>>() {});
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Il programma ha riscontrato un problema nel caricamento dei dati del menu", "ERRORE", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
            menu = new ArrayList<Pietanza>();
        }
        
        System.out.println("Ci sono " + sala.size() + " elementi in sala");
        System.out.println("Ci sono " + menu.size() + " elementi nel menu");
        for (Tavolo t: sala) {
            menuScroller2.addMenu(new BottoneTavolo(t, sala, menu));
            System.out.println("Aggiunto!");
        }
        menuScroller2.revalidate();
        menuScroller2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuScroller1 = new com.example.Gestionale.MenuScroller();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bAggiungiTavolo = new javax.swing.JButton();
        cbStatoTavolo = new javax.swing.JComboBox(StatoTavolo.values());
        lStatoTavolo = new javax.swing.JLabel();
        tfNumeroCoperti = new javax.swing.JTextField();
        lNumeroCoperti = new javax.swing.JLabel();
        tfNumeroPosti = new javax.swing.JTextField();
        lNumeroPosti = new javax.swing.JLabel();
        tfNumeroTavolo = new javax.swing.JTextField();
        lNumeriTavolo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bVisualizzaMenu = new javax.swing.JButton();
        menuScroller2 = new com.example.Gestionale.MenuScroller();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menuScroller1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(menuScroller1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(674, 250));
        setPreferredSize(new java.awt.Dimension(930, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(262, 624));

        bAggiungiTavolo.setText("Aggiungi tavolo");
        bAggiungiTavolo.addActionListener(this::bAggiungiTavoloActionPerformed);

        lStatoTavolo.setText("Stato tavolo");

        lNumeroCoperti.setText("Numero di coperti");

        lNumeroPosti.setText("Numero di posti");

        tfNumeroTavolo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lNumeriTavolo.setText("Numero tavolo");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Gestione tavoli");

        bVisualizzaMenu.setText("Visualizza menu");
        bVisualizzaMenu.addActionListener(this::bVisualizzaMenuActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bVisualizzaMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(bAggiungiTavolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(60, 60, 60))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNumeriTavolo)
                                .addComponent(lNumeroPosti)
                                .addComponent(lNumeroCoperti)
                                .addComponent(lStatoTavolo)
                                .addComponent(tfNumeroTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNumeroPosti, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNumeroCoperti, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbStatoTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addComponent(bAggiungiTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVisualizzaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(10, 10, 10)
                    .addComponent(lNumeriTavolo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfNumeroTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lNumeroPosti)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfNumeroPosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lNumeroCoperti)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfNumeroCoperti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lStatoTavolo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbStatoTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);
        getContentPane().add(menuScroller2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
        objectMapper.writeValue(new File("sala.json"), sala);
        objectMapper.writeValue(new File("menu.json"), menu);
        } catch (IOException ex) {
            System.out.println(ex);
            /*
            JOptionPane.showMessageDialog(this, "Qualcosa è andato storto nella chiusura del programma", "ERRORE", JOptionPane.ERROR_MESSAGE);
            return;
            */
        }
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void bVisualizzaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizzaMenuActionPerformed
        System.out.println("fired");
        
        ModificaMenuDialog d = new ModificaMenuDialog(this, menu);
        d.showDialog();
    }//GEN-LAST:event_bVisualizzaMenuActionPerformed

    private void bAggiungiTavoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAggiungiTavoloActionPerformed
        Tavolo tavolo = new Tavolo();
        try {
            tavolo.setNumTavolo(Integer.parseInt(tfNumeroTavolo.getText()));
            tavolo.setNumPosti(Integer.parseInt(tfNumeroPosti.getText()));
            tavolo.setNumCoperti(Integer.parseInt(tfNumeroCoperti.getText()));
            tavolo.setStatoTavolo((StatoTavolo) cbStatoTavolo.getSelectedItem());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Assicurati di aver inserito i dati correttamente", "ERRORE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.menuScroller2.addMenu(new BottoneTavolo(tavolo, sala, menu));
        sala.add(tavolo);
    }//GEN-LAST:event_bAggiungiTavoloActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAggiungiTavolo;
    private javax.swing.JButton bVisualizzaMenu;
    private javax.swing.JComboBox<String> cbStatoTavolo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lNumeriTavolo;
    private javax.swing.JLabel lNumeroCoperti;
    private javax.swing.JLabel lNumeroPosti;
    private javax.swing.JLabel lStatoTavolo;
    private com.example.Gestionale.MenuScroller menuScroller1;
    private com.example.Gestionale.MenuScroller menuScroller2;
    private javax.swing.JTextField tfNumeroCoperti;
    private javax.swing.JTextField tfNumeroPosti;
    private javax.swing.JTextField tfNumeroTavolo;
    // End of variables declaration//GEN-END:variables
}
