/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.Gestionale;

import java.awt.Color;
import java.awt.Container;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nano_machine
 */
public class BottoneTavolo extends javax.swing.JPanel {
    
    private Tavolo tavolo;
    private ArrayList<Tavolo> sala;
    ArrayList<Pietanza> menu;

    /**
     * Creates new form BottoneTavolo
     */
    public BottoneTavolo(Tavolo t, ArrayList<Tavolo> s, ArrayList<Pietanza> m) {
        initComponents();
        sala = s;
        menu = m;
        aggiornaComponente(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bElimina = new javax.swing.JButton();
        bElementoTavolo = new javax.swing.JButton();

        bElimina.setText("Elimina");
        bElimina.setMinimumSize(null);
        bElimina.addActionListener(this::bEliminaActionPerformed);

        bElementoTavolo.setText("Tavolo");
        bElementoTavolo.setPreferredSize(new java.awt.Dimension(120, 120));
        bElementoTavolo.addActionListener(this::bElementoTavoloActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bElementoTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bElementoTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bElementoTavoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElementoTavoloActionPerformed
        Ordinatore o = new Ordinatore((Frame)SwingUtilities.getAncestorOfClass(JFrame.class, this), menu, tavolo);
        o.showDialog();
        aggiornaComponente(tavolo);
    }//GEN-LAST:event_bElementoTavoloActionPerformed

    private void bEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaActionPerformed
         sala.remove(tavolo);
        tavolo = null;
        Container parent = getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
    }//GEN-LAST:event_bEliminaActionPerformed
    
    public void aggiornaTavolo(Tavolo t) {
        tavolo.setNumCoperti(t.getNumCoperti());
        tavolo.setNumCoperti(t.getNumCoperti());
    }
    
    private void aggiornaComponente(Tavolo t) {
        tavolo = t;
        
        bElementoTavolo.setText(String.format(
        """
        <html>
        Tavolo %d<br>
        %d posti<br>
        %d coperti
        </html>
        """, tavolo.getNumTavolo(), tavolo.getNumPosti(), tavolo.getNumCoperti()));
        
        switch(tavolo.getStatoTavolo()) {
            case StatoTavolo.LIBERO:
                bElementoTavolo.setBackground(Color.green);
                break;
            
            case StatoTavolo.ATTESA_CONTO:
                bElementoTavolo.setBackground(Color.yellow);
                break;
            
            case StatoTavolo.ATTESA_PAGAMENTO:
                bElementoTavolo.setBackground(Color.orange);
                break;
            
            case StatoTavolo.OCCUPATO:
                bElementoTavolo.setBackground(Color.red);
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bElementoTavolo;
    private javax.swing.JButton bElimina;
    // End of variables declaration//GEN-END:variables
}
