/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.Gestionale;

import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nano_machine
 */
public class BottoneMenu extends javax.swing.JPanel {
    
    private Pietanza pietanza;
    private ArrayList menu;
    
    
    /**
     * Creates new form bottoneMenu
     */
    public BottoneMenu(Pietanza p, ArrayList m) {
        initComponents();
        aggiornaComponente(p);
        menu = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bElementoMenu = new javax.swing.JButton();
        lNomePietanza = new javax.swing.JLabel();
        bElimina = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(120, 174));
        setMinimumSize(new java.awt.Dimension(120, 174));

        bElementoMenu.setText("Immagine");
        bElementoMenu.setPreferredSize(new java.awt.Dimension(120, 120));
        bElementoMenu.addActionListener(this::bElementoMenuActionPerformed);

        lNomePietanza.setText("Nome pietanza");

        bElimina.setText("Elimina");
        bElimina.setMinimumSize(null);
        bElimina.addActionListener(this::bEliminaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lNomePietanza))
                    .addComponent(bElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bElementoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bElementoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNomePietanza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bElementoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElementoMenuActionPerformed
        AggiungiAlMenuDialog e = new AggiungiAlMenuDialog((Frame)SwingUtilities.getAncestorOfClass(JFrame.class, this), pietanza);
        int returnValue = e.showDialog();
        if (returnValue == AggiungiAlMenuDialog.CONFERMA) {
            Pietanza p = e.getPietanza();
            menu.set(menu.indexOf(pietanza), p);
            aggiornaComponente(p);
        }
    }//GEN-LAST:event_bElementoMenuActionPerformed

    private void bEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaActionPerformed
        menu.remove(pietanza);
        File f = new File(pietanza.getPathImmagine());
        
        //Elimina l'immagine associata alla pietanza
        if (f.exists()) {
            f.delete();
        }
        
        pietanza = null;
        Container parent = getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
    }//GEN-LAST:event_bEliminaActionPerformed
    
    private void aggiornaComponente(Pietanza p) {
        pietanza = p;
        if (p.getPathImmagine() != null) {
            File f = new File(p.getPathImmagine());
            try {
                bElementoMenu.setIcon(new ImageIcon(ImageIO.read(f)));//converte il file in icona is scala
            } catch (IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Si è verificato un problema aprendo il file immagine.", "ERRORE", JOptionPane.WARNING_MESSAGE);
            }          
            bElementoMenu.setText(null);
        }
        lNomePietanza.setText(p.getNomePietanza());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bElementoMenu;
    private javax.swing.JButton bElimina;
    private javax.swing.JLabel lNomePietanza;
    // End of variables declaration//GEN-END:variables
}
