/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.Gestionale;

import java.util.ArrayList;
import java.util.function.Consumer;
import javax.swing.ImageIcon;

/**
 *
 * @author nano_machine
 */
public class BottoneMenuOrdinazione extends javax.swing.JPanel {
    Pietanza pietanza;
    ArrayList<Pietanza> ordine;
    //Signal onAggiunto;
    Consumer onAggiunto;

    /**
     * Creates new form BottoneMenuOrdinazione
     */
    public BottoneMenuOrdinazione(Pietanza p, Consumer<Pietanza> onPietanzaAggiunta) {
        this.pietanza = p;
        this.ordine = ordine;
        this.onAggiunto = onPietanzaAggiunta;
        initComponents();
        aggiornaComponente(p);
    }
    
    private void fireAggiunto() {
        onAggiunto.accept(pietanza);
    }
    
    void setOnAggiunto(Consumer<Pietanza> pietanzaAggiuntaListener) {
        onAggiunto = pietanzaAggiuntaListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNomePietanza = new javax.swing.JLabel();
        bElementoMenu = new javax.swing.JButton();

        lNomePietanza.setText("Nome pietanza");

        bElementoMenu.setText("Immagine");
        bElementoMenu.setPreferredSize(new java.awt.Dimension(120, 120));
        bElementoMenu.addActionListener(this::bElementoMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lNomePietanza))
                    .addComponent(bElementoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bElementoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNomePietanza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bElementoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElementoMenuActionPerformed
        fireAggiunto();
    }//GEN-LAST:event_bElementoMenuActionPerformed
    
    private void aggiornaComponente(Pietanza p) {
        pietanza = p;
        if (p.getPathImmagine() != null) {
            bElementoMenu.setIcon(new ImageIcon(p.getPathImmagine()));
            bElementoMenu.setText(null);
        }
        lNomePietanza.setText(p.getNomePietanza());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bElementoMenu;
    private javax.swing.JLabel lNomePietanza;
    // End of variables declaration//GEN-END:variables
}
