/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.Gestionale;

import java.awt.Container;
import java.util.function.Consumer;

/**
 *
 * @author nano_machine
 */
public class ElementoListaOrdinazione extends javax.swing.JPanel {
    Pietanza pietanza;
    Consumer<Pietanza> pietanzaEliminataTrigger;

    /**
     * Creates new form ElementoListaOrdinazione
     */
    public ElementoListaOrdinazione(Pietanza p, Consumer<Pietanza> c) {
        initComponents();
        
        pietanza = p;
        pietanzaEliminataTrigger = c;
        
        lNomePietanza.setText(pietanza.getNomePietanza());
        lPrezzo.setText("€" + pietanza.getPrezzo());
    }
    
    public void onPietanzaEliminata() {
        Container parent = getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
        pietanzaEliminataTrigger.accept(pietanza);
        pietanza = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNomePietanza = new javax.swing.JLabel();
        lPrezzo = new javax.swing.JLabel();
        lBottoneElimina = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(32767, 45));
        setMinimumSize(new java.awt.Dimension(350, 45));

        lNomePietanza.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lNomePietanza.setText("Nome Pietanza");

        lPrezzo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lPrezzo.setText("Prezzo");

        lBottoneElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BottoneEliminaPietanzaImmagine.png"))); // NOI18N
        lBottoneElimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBottoneEliminaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNomePietanza, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBottoneElimina))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lBottoneElimina)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNomePietanza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lBottoneEliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBottoneEliminaMouseClicked
        onPietanzaEliminata();
    }//GEN-LAST:event_lBottoneEliminaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBottoneElimina;
    private javax.swing.JLabel lNomePietanza;
    private javax.swing.JLabel lPrezzo;
    // End of variables declaration//GEN-END:variables
}
