/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.example.Gestionale;

import com.google.common.collect.EnumHashBiMap;
import com.google.common.collect.HashBiMap;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author nano_machine
 */
public class ModificaMenuDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificaMenuDialog.class.getName());
    
    private ArrayList<Pietanza> menu;
    private Frame parent;
    private EnumHashBiMap<Portata, ButtonModel> portataBottone;

    /**
     * Creates new form ModificaMenuDialog
     */
    public ModificaMenuDialog(java.awt.Frame parent, ArrayList<Pietanza> menu) {
        super(parent, true);
        
        this.menu = menu;
        
        initComponents();
        
        for (Pietanza i: this.menu) {
            menuScroller3.addMenu(new BottoneMenu(i, menu));
        }
        
        this.portataBottone = EnumHashBiMap.create(Portata.class);
        //inizializza un bottone per ogni categoria di pietanza nell'Enum Portata
        for (Portata x : Portata.values()) {
            JToggleButton b = new JToggleButton(x.toString());
            b.setMinimumSize(new Dimension(190, 50));
            b.setPreferredSize(new Dimension(190, 50));
            b.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    bSelezioneClicked(evt);
                }
            });
            buttonGroup1.add(b);
            pPortate.add(b);
            portataBottone.put(x, b.getModel());
        }
        
        pPortate.revalidate();
        pPortate.repaint();
        menuScroller3.revalidate();
        menuScroller3.repaint();
    }
    
    public void showDialog() {
        setLocationRelativeTo(parent);
        setVisible(true);
    }
    
    private void bSelezioneClicked(java.awt.event.MouseEvent evt) {
        //potrebbe essere conveniente processare tutti i panel all'apertura della finestra di ordinazione
        //per evitare overhead ogni volta che si preme un pulsante per cambiare categoria
        //ulteriore soluzione sarebbe cachare il panel già processati e ricaricarli se l'utente ritorna sulla categoria (da provare)
        menuScroller3.removeAllButtons();
        Portata portata = (Portata) portataBottone.inverse().get(((JToggleButton) evt.getSource()).getModel()); //trova la portata corrispondente al bottone cliccato
        for (Pietanza i : menu) {
            if(i.getPortata() == portata) {
                menuScroller3.addMenu(new BottoneMenu(i, menu));
            }
        }
        menuScroller3.revalidate();
        menuScroller3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        spPortate2 = new javax.swing.JScrollPane();
        pPortate = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        menuScroller3 = new com.example.Gestionale.MenuScroller();
        jPanel3 = new javax.swing.JPanel();
        bAggiungiAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        spPortate2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spPortate2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spPortate2.setPreferredSize(new java.awt.Dimension(212, 100));

        pPortate.setMaximumSize(new java.awt.Dimension(200, 32767));
        pPortate.setMinimumSize(new java.awt.Dimension(200, 100));
        pPortate.setPreferredSize(new java.awt.Dimension(200, 716));

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setSelected(true);
        jToggleButton3.setText("Tutti");
        jToggleButton3.setMaximumSize(new java.awt.Dimension(188, 50));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(188, 50));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(188, 50));
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);
        pPortate.add(jToggleButton3);

        spPortate2.setViewportView(pPortate);

        jPanel2.add(spPortate2, java.awt.BorderLayout.LINE_START);
        jPanel2.add(menuScroller3, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(922, 57));

        bAggiungiAlMenu.setText("Aggiungi al menu");
        bAggiungiAlMenu.setMaximumSize(new java.awt.Dimension(175, 45));
        bAggiungiAlMenu.setMinimumSize(new java.awt.Dimension(175, 45));
        bAggiungiAlMenu.setPreferredSize(new java.awt.Dimension(175, 45));
        bAggiungiAlMenu.addActionListener(this::bAggiungiAlMenuActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(742, Short.MAX_VALUE)
                .addComponent(bAggiungiAlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAggiungiAlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        menuScroller3.removeAllButtons();
        for (Pietanza i : menu) {
            menuScroller3.addMenu(new BottoneMenu(i, menu));
        }
        menuScroller3.revalidate();
        menuScroller3.repaint();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void bAggiungiAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAggiungiAlMenuActionPerformed
        AggiungiAlMenuDialog d = new AggiungiAlMenuDialog((Frame) SwingUtilities.getAncestorOfClass(JFrame.class, this));
        int returnValue = d.showDialog();
        if (returnValue == AggiungiAlMenuDialog.CONFERMA) {
            Pietanza p = d.getPietanza();
            menu.add(p);
            if (p.getPortata() == portataBottone.inverse().get((buttonGroup1.getSelection())) || buttonGroup1.getSelection() == jToggleButton3.getModel()) {
                BottoneMenu bm = new BottoneMenu(p, menu);
                menuScroller3.addMenu(bm);
            }
        }
    }//GEN-LAST:event_bAggiungiAlMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModificaMenuDialog dialog = new ModificaMenuDialog(new javax.swing.JFrame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAggiungiAlMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton3;
    private com.example.Gestionale.MenuScroller menuScroller3;
    private javax.swing.JPanel pPortate;
    private javax.swing.JScrollPane spPortate2;
    // End of variables declaration//GEN-END:variables
}
