/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.example.Gestionale;

import com.google.common.collect.EnumHashBiMap;
import com.google.common.collect.ImmutableBiMap;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Vector;
import java.util.function.Consumer;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nano_machine
 */
public class Ordinatore extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ordinatore.class.getName());

    private EnumHashBiMap<Portata, ButtonModel> portataBottone;
    private ArrayList<Pietanza> menu;
    private Tavolo tavolo;
    private Frame parent;
    //private Signal pietanzaAggiuntaListener = () -> onPietanzaAggiunta();
    private Consumer<Pietanza> pietanzaAggiuntaListener = p -> onPietanzaAggiunta(p);
    private Consumer<Pietanza> pietanzaEliminataListener = p -> onPietanzaEliminata(p);
    
    /**
     * Creates new form Ordinatore
     */
    public Ordinatore(java.awt.Frame parent, ArrayList<Pietanza> menu, Tavolo tavolo) {
        super(parent, true);
        initComponents();
        
        this.parent = parent;
        this.menu = menu;
        this.tavolo = tavolo;
        this.portataBottone = EnumHashBiMap.create(Portata.class);
        
        //inizializza un bottone per ogni categoria di pietanza nell'Enum Portata
        for (Portata x : Portata.values()) {
            JToggleButton b = new JToggleButton(x.toString());
            b.setMinimumSize(new Dimension(190, 50));
            b.setPreferredSize(new Dimension(190, 50));
            b.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    bSelezioneClicked(evt);
                }
            });
            
            buttonGroup1.add(b);
            pPortate.add(b);
            portataBottone.put(x, b.getModel());
        }
        
        //inizializza lista pietanza
        for (Pietanza i: this.menu) {
            menuScroller3.addMenu(new BottoneMenuOrdinazione(i, pietanzaAggiuntaListener));
        }
        
        //inizializza lista pietanze odinate
        for (Object i: this.tavolo.getOrdine()) {
            jPanel1.add(new ElementoListaOrdinazione((Pietanza)i, pietanzaEliminataListener));
        }
        
        //inizializza pannello modifica tavolo
        tfNumeroTavolo.setText(Integer.toString(tavolo.getNumTavolo()));
        tfNumeroPosti.setText(Integer.toString(tavolo.getNumPosti()));
        tfNumeroCoperti.setText(Integer.toString(tavolo.getNumCoperti()));
        cbStatoTavolo.setSelectedItem(tavolo.getStatoTavolo());

        
        jPanel1.revalidate();
        jPanel1.repaint();
        pPortate.revalidate();
        pPortate.repaint();
        menuScroller3.revalidate();
        menuScroller3.repaint();
        
        
    }
    
    public void showDialog() {
        setLocationRelativeTo(parent);
        this.setVisible(true);
    }
    
    private void bSelezioneClicked(java.awt.event.MouseEvent evt) {
        //potrebbe essere conveniente processare tutti i panel all'apertura della finestra di ordinazione
        //per evitare overhead ogni volta che si preme un pulsante per cambiare categoria
        //ulteriore soluzione sarebbe cachare il panel già processati e ricaricarli se l'utente ritorna sulla categoria (da provare)
        menuScroller3.removeAllButtons();
        Portata portata = portataBottone.inverse().get(((JToggleButton) evt.getSource()).getModel()); //trova la portata corrispondente al bottone cliccato
        for (Pietanza i : menu) {
            if(i.getPortata() == portata) {
                menuScroller3.addMenu(new BottoneMenuOrdinazione(i, pietanzaAggiuntaListener));
            }
        }
        menuScroller3.revalidate();
        menuScroller3.repaint();
    }
    
    private void onPietanzaAggiunta(Pietanza p) {
        tavolo.getOrdine().add(p);
        jPanel1.add(new ElementoListaOrdinazione(p, pietanzaEliminataListener));
        jPanel1.revalidate();
        jPanel1.repaint();
        //System.out.println("OOOOOOH MY GOOOOD!!!");
    }
    
    private void onPietanzaEliminata(Pietanza p) {
        tavolo.getOrdine().remove(p);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        spPortate2 = new javax.swing.JScrollPane();
        pPortate = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        menuScroller3 = new com.example.Gestionale.MenuScroller();
        jPanel3 = new javax.swing.JPanel();
        tfNumeroTavolo = new javax.swing.JTextField();
        tfNumeroPosti = new javax.swing.JTextField();
        tfNumeroCoperti = new javax.swing.JTextField();
        lNumeroTavolo = new javax.swing.JLabel();
        lNumeroPosti = new javax.swing.JLabel();
        lNumeroCoperti = new javax.swing.JLabel();
        cbStatoTavolo = new javax.swing.JComboBox(StatoTavolo.values());
        lStatoTavolo = new javax.swing.JLabel();
        tfTotale = new javax.swing.JTextField();
        lTotale = new javax.swing.JLabel();
        bCalcolaTotale = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane2.setMinimumSize(new java.awt.Dimension(1400, 200));
        jSplitPane2.setPreferredSize(new java.awt.Dimension(1400, 718));
        jSplitPane2.setDividerLocation(896);

        jPanel2.setMinimumSize(new java.awt.Dimension(796, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(796, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        spPortate2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spPortate2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spPortate2.setPreferredSize(new java.awt.Dimension(212, 100));

        pPortate.setMaximumSize(new java.awt.Dimension(200, 32767));
        pPortate.setMinimumSize(new java.awt.Dimension(200, 100));
        pPortate.setPreferredSize(new java.awt.Dimension(200, 716));

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setSelected(true);
        jToggleButton3.setText("Tutti");
        jToggleButton3.setMaximumSize(new java.awt.Dimension(190, 50));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(190, 50));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(190, 50));
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);
        pPortate.add(jToggleButton3);

        spPortate2.setViewportView(pPortate);

        jPanel2.add(spPortate2, java.awt.BorderLayout.LINE_START);
        jPanel2.add(menuScroller3, java.awt.BorderLayout.CENTER);

        jPanel3.setMinimumSize(new java.awt.Dimension(74, 100));

        lNumeroTavolo.setText("Numero tavolo");

        lNumeroPosti.setText("Numero posti");

        lNumeroCoperti.setText("Numero coperti");

        lStatoTavolo.setText("Stato tavolo");

        tfTotale.setEditable(false);
        tfTotale.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lTotale.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lTotale.setText("Totale");

        bCalcolaTotale.setText("Calcola totale");
        bCalcolaTotale.addActionListener(this::bCalcolaTotaleActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNumeroCoperti)
                    .addComponent(lStatoTavolo)
                    .addComponent(lNumeroPosti)
                    .addComponent(lNumeroTavolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfNumeroTavolo)
                    .addComponent(tfNumeroPosti, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbStatoTavolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNumeroCoperti))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTotale)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTotale)
                            .addComponent(bCalcolaTotale, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumeroTavolo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroPosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumeroPosti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumeroCoperti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNumeroCoperti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStatoTavolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lStatoTavolo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lTotale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCalcolaTotale)
                        .addGap(19, 19, 19))))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jSplitPane2.setLeftComponent(jPanel2);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(jPanel1);

        jSplitPane2.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        menuScroller3.removeAllButtons();
        for (Pietanza i : menu) {
            menuScroller3.addMenu(new BottoneMenuOrdinazione(i, pietanzaAggiuntaListener));
        }
        menuScroller3.revalidate();
        menuScroller3.repaint();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
            tavolo.setNumTavolo(Integer.parseInt(tfNumeroTavolo.getText()));
            tavolo.setNumPosti(Integer.parseInt(tfNumeroPosti.getText()));
            tavolo.setNumCoperti(Integer.parseInt(tfNumeroCoperti.getText()));
            tavolo.setStatoTavolo((StatoTavolo) cbStatoTavolo.getSelectedItem());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Alcuni dati del tavolo non sono stati aggiornati poichè la formattazione del testo è errata", "ERRORE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void bCalcolaTotaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcolaTotaleActionPerformed
        float tot = 0;
        
        for (Pietanza p : tavolo.getOrdine())
            tot += p.getPrezzo();
        
        try {
            tot += Float.parseFloat(tfNumeroCoperti.getText()) * tavolo.PREZZO_COPERTO;
            tfTotale.setText(Float.toString(tot));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Assicurati di aver inserito un valore valido nel campo dei coperti", "ERRORE", JOptionPane.ERROR_MESSAGE);
            tfTotale.setText("0");
        }
    }//GEN-LAST:event_bCalcolaTotaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Ordinatore dialog = new Ordinatore(new javax.swing.JFrame(), null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcolaTotale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbStatoTavolo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lNumeroCoperti;
    private javax.swing.JLabel lNumeroPosti;
    private javax.swing.JLabel lNumeroTavolo;
    private javax.swing.JLabel lStatoTavolo;
    private javax.swing.JLabel lTotale;
    private com.example.Gestionale.MenuScroller menuScroller3;
    private javax.swing.JPanel pPortate;
    private javax.swing.JScrollPane spPortate2;
    private javax.swing.JTextField tfNumeroCoperti;
    private javax.swing.JTextField tfNumeroPosti;
    private javax.swing.JTextField tfNumeroTavolo;
    private javax.swing.JTextField tfTotale;
    // End of variables declaration//GEN-END:variables
}
